- name: Xfce set theme
  become_user: '{{ user.name }}'
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  community.general.xfconf :
    channel: "xsettings"
    property: /Net/ThemeName
    value: '{{ xfce.theme_name }}'
    value_type: string