- name: Xfce panel. Configuring menu icon
  become_user: '{{ user.name }}'
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  community.general.xfconf :
    channel: "xfce4-panel"
    property: /plugins/plugin-1/button-icon
    value: '{{ xfce.xfce4_panel.button_icon }}'
    value_type: string


- name: Xfce panel. Configuring button title
  become_user: '{{ user.name }}'
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  community.general.xfconf :
    channel: "xfce4-panel"
    property: /plugins/plugin-1/show-button-title
    value: '{{ xfce.xfce4_panel.show_button_title }}'
    value_type: bool


- name: Xfce panel. Removing panel 2
  # It removes only reference to the panel 2...
  become_user: '{{ user.name }}'
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  community.general.xfconf:
    channel: "xfce4-panel"
    property: /panels
    value: 1
    value_type: int
    force_array: true
