- ansible.builtin.import_tasks: check_user_bus.yml
  name: check_user_bus

- name: Xfce set xsettings theme
  become_user: '{{ user.name }}'
  environment:
    DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  community.general.xfconf :
    channel: "xsettings"
    property: /Net/ThemeName
    value: '{{ xfce.xsettings.theme_name }}'
    value_type: string
  when: run_user_bus_socket.stat.exists