---

- name: Install arch linux for gaming
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: general, tags: ['general'] }
    - { role: users, tags: ['users'] }
    - { role: systemd-network, tags: ['systemd-network'] }
    - { role: xfce, tags: ['xfce'] }
