---

- name: Install arch linux for gaming
  hosts: hosts
  connection: local
  become: true

  roles:
    - { role: general, tags: ['general'] }
    - { role: users, tags: ['users'] }
    - { role: systemd-network, tags: ['systemd-network'] }
    - { role: systemd-network-wifi, tags: ['systemd-network-wifi'] }
    - { role: xorg, tags: ['xorg'] }
    - { role: xfce, tags: ['xfce'] }
    - { role: xfce-configure, tags: ['xfce-configure'] } # Ignored if X11 is not run user
    - { role: chromium, tags: ['chromium'] }
    - { role: firefox, tags: ['firefox'] }
    - { role: pulseaudio, tags: ['pulseaudio'] }
    - { role: blacklist-nouveau, tags: ['blacklist-nouveau'] }
    - { role: firewall-ufw, tags: ['firewall-ufw'] }
    - { role: firewall-gufw, tags: ['firewall-gufw'] }
    - { role: steam, tags: ['steam'] }