---

- name: Install Pulseaudio
  community.general.pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pavucontrol
      - sof-firmware
    state: present
