---

- name: Install network tools
  community.general.pacman:
    name:
      - ethtool
      - wpa_supplicant
      - nmap
      - networkmanager
      - network-manager-applet
      - networkmanager-openconnect
      - networkmanager-openvpn
    state: present

- name: Enable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: started
    enabled: true