---

- name: Enable multilib in /etc/pacman.conf
  community.general.ini_file:
    path: /etc/pacman.conf
    section: multilib
    option: Include
    value: /etc/pacman.d/mirrorlist

- name: Enable multilib-testing in /etc/pacman.conf
  community.general.ini_file:
    path: /etc/pacman.conf
    section: multilib-testing
    option: Include
    value: /etc/pacman.d/mirrorlist

- name: Perform full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install lib32-nvidia-utils
  community.general.pacman:
    name:
      - lib32-nvidia-utils
    state: present