---

- name: Generate locale
  locale_gen:
    name: '{{ locale }}'
    state: present

- name: Set locale
  lineinfile:
    path: /etc/locale.conf
    create: True
    state: present
    regexp: "^LANG"
    line: 'LANG={{ locale }}'