---

- name: Pacman mirrorlist setup
  ansible.builtin.copy:
    src: mirrorlist
    dest: /etc/pacman.d/

- name: Update pacman package cache
  pacman:
    update_cache: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Perform full system upgrade
  pacman:
    update_cache: true
    upgrade: true

- name: Install extra for pacman and aur packages
  ansible.builtin.package:
    name:
      - pkgfile
    state: present
  notify:
    - pkgfile update