---

- name: Install UFW
  community.general.pacman:
    name:
      - ufw
    state: present

- name: Enable UFW systemd service
  ansible.builtin.service: name=ufw state=restarted enabled=true

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny