---

- name: Create group user.group if it does not exists
  ansible.builtin.group:
    name: "{{ user.group }}"
    state: present
  when: user.name is defined

- name: Create user user.name if it does not exists
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - "{{ user.group }}"
      - network
      - systemd-journal
      - uucp
      - tty
    append: true
    system: false
    createhome: true
    home: /home/{{ user.name }}
  when: user.name is defined

- name: Install polkit
  community.general.pacman:
    name:
      - polkit
    state: present

- name: Install grml-zsh-config if zsh was set as shell
  community.general.pacman:
    name:
      - grml-zsh-config
    state: present
  when: user.shell == "/bin/zsh" or user.shell == "/usr/bin/zsh"

- name: Configure zsh to point to grml-zsh-config
  ansible.builtin.file:
    src: /etc/skel/.zshrc
    dest: "/home/{{ user.name }}/.zshrc"
    owner: "{{ user.shell }}"
    group: "{{ user.shell }}"
    state: link
  when: user.shell == "/bin/zsh" or user.shell == "/usr/bin/zsh"